apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
      - name: init-sites-volume
        image: drupal:latest
        command: ['/bin/bash', '-c', 'cp -r /var/www/html/sites/* /mnt/sites/']
        volumeMounts:
        - name: drupal-storage
          mountPath: /mnt/sites
      containers:
      - name: drupal
        image: drupal:latest
        ports:
        - containerPort: 80
        env:
        - name: DRUPAL_DB_HOST
          value: "mysql-service"
        - name: DRUPAL_DB_NAME
          value: "drupaldb"
        - name: DRUPAL_DB_USER
          value: "drupaluser"
        - name: DRUPAL_DB_PASSWORD
          value: "drupalpass"
        volumeMounts:
        - name: drupal-storage
          mountPath: /var/www/html/sites
      volumes:
      - name: drupal-storage
        persistentVolumeClaim:
          claimName: drupal-pvc